export const INIT_STATE = 'INIT_BANK_DETAILS_STATE';
export const RESET_ERROR = 'RESET_BANK_DETAILS_ERROR';

export const GET_BANK_DETAILS_LOADING = 'GET_BANK_DETAILS_DATA_LOADING';
export const GET_BANK_DETAILS_SUCCESS = 'GET_BANK_DETAILS_DATA_SUCCESS';
export const GET_BANK_DETAILS_ERROR = 'GET_BANK_DETAILS_DATA_ERROR';

export const CACHE_SUCCESS = 'CACHE_SUCCESS' ;